### PR TITLE
Org

### PR DESCRIPTION
**Pull request by affeldt-aist**
forgot to add index.html in the previous PR, my bad

### CODE REVIEW

**Comment by amahboubi** [comment]
This PR has a conflict now... @affeldt-aist, could you solve it ? Also, can you confirm that file index.old.html, push in the previous PR is now useless?

**Comment by amahboubi** [comment]
In fact, since .html files are now supposed to be generated from the .org ones, is it sensible at all to keep the .html ones versioned?

**Comment by CohenCyril** [comment]
> In fact, since .html files are now supposed to be generated from the .org ones, is it sensible at all to keep the .html ones versioned?

github needs them to display the website (it does not do the generation itself afaik)

**Comment by affeldt-aist** [comment]
I confirm that index.old.html is useless.

I have not yet understood how to solve the conflict myself.

**Comment by amahboubi** [comment]
Ok. This is  a point I misunderstood this morning. So this should be very clear in the README.md I guess.

**Comment by amahboubi** [comment]
@affeldt-aist  What about just:
- reverting your last commit?
- removing the .old.html
in this PR.
Then we will take care of re-generating the .html.

**Pull request merged**
