### PR TITLE
tentative math-comp analysis doc

### PR DESCRIPTION
**Pull request by affeldt-aist**
This PR adds a directory `analysis` with a subdirectory `html_doc_0_3_12`.
It contains the documentation generated from the mathcomp-analysis source code using the scripts from MathComp.
@CohenCyril @gares

### CODE REVIEW

**Comment by gares** [comment]
I think the best way to review this is to merge and browse it.

**Comment by affeldt-aist** [comment]
> I think the best way to review this is to merge and browse it.

It is also easier for other developers to browse it once it is merged.
We do not need to publicize it right now and have some time to clean it.

**Comment by gares** [comment]
online: https://math-comp.github.io/analysis/htmldoc_0_3_12/

**Comment by gares** [comment]
a glitch at the bottom: https://math-comp.github.io/analysis/htmldoc_0_3_12/mathcomp.analysis.boolp.html

**Pull request merged**
