### PR TITLE
port the list of papers from the wiki to the org format

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by affeldt-aist** [comment]
I have just ported the list of papers that is on the math-comp wiki using the org format.
I have not added any new contents but tried to put papers into categories.

**Comment by amahboubi** [comment]
Hello @affeldt-aist. In fact your PR also touches the index* files, and thus now conflicts with the current master. Do you want me to resolve the conflicts?

**Comment by affeldt-aist** [comment]
> Do you want me to resolve the conflicts?
Yes, please. I only modified a single link in index.org...

**Comment by amahboubi** [comment]
It is indeed the only meaningful change, but it triggers many more in index.html in fact (years of Free Software Foundation copyright, as you noted, name of author, identifiers, etc.).

In fact I just added you as a collaborator for this repo. Can you now resolve the conflicts yourself?

**Comment by CohenCyril** [comment]
I don't understand what is happening here... I'm totally ok with reynald having commit rights, but I don't understand why hr does not do a simple rebase and force push on his own side. (Which would be the recommended procedure)

**Comment by amahboubi** [comment]
I agree, this is indeed what I asked yesterday in PR #2, but then did not understand myself what happened in that PR. But I think my proposal to grant @affeldt-aist push access to the repo is even more sensible.

**Comment by amahboubi** [comment]
@affeldt-aist, can you confirm that if I merge #6 I can also close the present #5 ?

**Comment by affeldt-aist** [comment]
Yes, it is the same contents.

**Comment by amahboubi** [comment]
This PR was subsumed by #6.

**Pull request closed without merging**
